app/sell/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, TextField
from flask_wtf.file import FileField, FileRequired, FileAllowed
from ..import images
from wtforms.validators import Required, Length, Regexp, EqualTo
from wtforms import ValidationError
from ..models import Item, Cate

class ItemForm(FlaskForm):
    image=FileField('image', validators=[FileAllowed(images,'only images'), FileRequired('please choose an image')])
    name = StringField('Name')
    price = IntegerField('Price')
    num = IntegerField('Num')
    desc = TextField('Description')
    cate = StringField('Category')
    submit = SubmitField('Upload')

app/sell/__init__.py
from flask import Blueprint

sell = Blueprint('sell', __name__)

from . import views

app/sell/views.py
from flask import render_template, redirect, url_for, flash
from . import sell
from .. import db, images
from ..models import Item, Cate, Order_Item, Order
from flask_login import login_required, current_user
from .forms import ItemForm


@sell.route('/upload', methods=['GET', 'POST'])
@login_required
def upload():
    form = ItemForm()
    if form.validate_on_submit():
        cate = Cate.query.filter_by(name=form.cate.data).first()
        if not cate:
            cate = Cate(name=form.cate.data)
            db.session.add(cate)
            db.session.commit()
            cate = Cate.query.filter_by(name=form.cate.data).first()

        item = Item(name=form.name.data,
                    price=form.price.data,
                    num=form.num.data,
                    desc=form.desc.data,
                    cate_id=cate.id,
                    owner_id=current_user.id
                    )
        db.session.add(item)
        db.session.commit()
        filename = images.save(form.image.data, name=str(item.id)+'.')
        item.img = filename
        db.session.add(item)
        db.session.commit()
        flash("Upload Success.")
        return redirect(url_for('sell.upload'))
    return render_template("sell/upload.html", form=form)


@sell.route('/order')
@login_required
def order():
    # orders = Order.query.filter_by(owner_id=current_user.id).all()
    orders = db.session.execute("SELECT * FROM orders WHERE orders.owner_id="+str(current_user.id)).fetchall()
    itemslist = []
    img_dict = {}
    for order in orders:
        # items = Order_Item.query.filter_by(order_id=order.id).all()
        items = db.session.execute("SELECT * FROM order_item WHERE order_item.order_id="+str(order.id)).fetchall()
        for item in items:
            # item_img = Item.query.filter_by(id=item.item_id).first().img
            item_imgg = db.session.execute("SELECT * FROM items WHERE items.id=" + str(item.item_id)).fetchone()
            item_img = item_imgg.img
            img_dict[item.item_id] = item_img
        itemslist.append(items)
    return render_template("sell/order.html", orders=orders, itemslist=itemslist, images=images, img_dict=img_dict)


@sell.route('/deliver/<int:order_id>')
@login_required
def deliver(order_id):
    order = Order.query.filter_by(id=order_id).first_or_404()
    if order.owner_id == current_user.id and order.status == 1:
        order.status = 2
        db.session.add(order)
        db.session.commit()
        flash("Deliver Success")
    return redirect(url_for("sell.order"))

app/templates/sell/order.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}

<style>
    .td-font{
        line-height: 90px;
    }
</style>

<div class="page-header">
    <h1>已出售的订单</h1>
</div>
<div class="container main-container">
    {% for order in orders %}
        <div>下单时间 : {{ order.date }}</div>
        <table class="table table-striped">
            <thead>
                    <tr>
                        <td><b>商品图像</b></td>
                        <td><b>序号</b></td>
                        <td><b>数量</b></td>
                    </tr>
                </thead>
                <tbody>
                {% for item in itemslist[loop.index0] %}
                    <tr>
                        <td><span><img src="{{ images.url(img_dict[item.item_id])}}" height="100px" width="100px"></span></td>
                        <td><span class="td-font">{{ item.item_id }}</span></td>
                        <td><span class="td-font">{{ item.num }}</span></td>
                        <td><a href="{{ url_for('public.item', item_id=item.id) }}" class="td-font">详情</a></td>
                    </tr>
                {% endfor %}
                </tbody>
        </table>
        <div>
            {% if order.status == 0 %}未付款
            {% elif order.status == 1 %}未发货，<a href="{{ url_for('sell.deliver', order_id=order.id) }}">发货</a>
            {% elif order.status == 2 %}已发货
            {% else %}已完成
            {% endif %}
        </div>
        <br>
    {% endfor %}
</div>
<br>
{% endblock %}

app/templates/sell/upload.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Upload{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>上传商品</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}